# Generated by Django 5.2 on 2025-05-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0003_alter_taskmodel_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='dayInput',
            field=models.CharField(default='вторник', max_length=350, verbose_name='Ввод дня'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='overworkInput',
            field=models.CharField(default='арьуз, вторник, 4| дыня, вторник, 2', max_length=350, verbose_name='Ввод записей'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='taskQuestion',
            field=models.CharField(default='Сколько записей о переработках в день Х?', max_length=350, verbose_name='Формулировка задачи'),
        ),
    ]
