# Generated by Django 5.2 on 2025-05-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskQuestion', models.CharField(default='Сколько записей о переработках в день Х?', verbose_name='Формулировка задачи')),
                ('overworkInput', models.CharField(default='арьуз, вторник, 4| дыня, вторник, 2', verbose_name='Ввод записей')),
                ('dayInput', models.CharField(default='вторник', verbose_name='Ввод дня')),
                ('result', models.CharField(default='В данный день не было переработок', verbose_name='Результат')),
                ('currenttime', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
        ),
    ]
