# Generated by Django 5.2 on 2025-05-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageTitle', models.CharField(default='Заголовок', verbose_name='Заголовок')),
                ('PageUrl', models.CharField(default='default', verbose_name='Ссылка')),
                ('PagePriority', models.IntegerField(default=1, verbose_name='Приоритет')),
                ('PageContent', models.TextField(default='<p>Привет</p>', verbose_name='Основное содержание страницы')),
                ('currenttime', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Контент текущей страницы',
                'verbose_name_plural': 'Уникальный контент страниц',
                'ordering': ('-PagePriority',),
            },
        ),
    ]
