# Generated by Django 5.2 on 2025-05-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='PageTitle',
            field=models.CharField(default='Заголовок', max_length=350, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='page',
            name='PageUrl',
            field=models.CharField(default='default', max_length=350, verbose_name='Ссылка'),
        ),
    ]
